#!/bin/bash

set -e -o pipefail

# conditional for DEBUG mode
if [ "${DEBUG}" = 1 ]; then
    set -x
elif [ "${DRYRUN}" = 1 ]; then
    RUNTEST=1
fi

# variables
KFENV=https://raw.githubusercontent.com/glayneon/kfinit/main/kfenv

# loading environtal variables using curl
curlsource() {
    LOADING_FILE=$(basename $1)
    echo "[INFO] ::: Loading Environtal Variables from ${LOADING_FILE} ..."
    f=$(mktemp -t curlsource.XXX)
    curl -o "$f" -sSL "$1"
    source "$f"
    rm -f "$f"
}

# import all required variables for installation
curlsource ${KFENV}
curlsource ${FUNCTIONS}

# Installation Flag: true or false
if [ -z "${KF_VERSION}" ]; then
    usage
    exit 1
fi

# install GUM
install_gum

# show title along with the current mode
show_title ${PROJECT_NAME}

# Install Kubeflow components in order
# 0. clone git and working directory
info clone_git_repo
info 'cd ${WORK_DIR}'

# 1. cert-manager
info install_cert_manager

# 2. istio
info install_istio

# 3. Oauth2-proxy
info install_oauth2_proxy

# 4. dex
info install_dex



# Check the service is running
if [ "${DRYRUN}" != 1 ]; then
    info "::: Start - Running Kubeflow service for about 90 seconds ..."
    # gum spin --spinner line --title "::: Running Kubeflow service... " -- systemctl start rke2-${RKE2_TYPE}.service
    gum spin --spinner line --title "::: Running Kubeflow service... " sleep 10
    # journalctl -u rke2-server -f

    double_line
    info "::: Finish - Running Kubeflow service ... "
    sleep ${DELAY}
fi

# install cert-manager, argocd-cli and longhorn
# install_tools_cli

# generate self-signed cert
# gen_cert

if [ "${DRYRUN}" != 1 ]; then
    # Ending
    double_line
    info "::: Finish installation of Kubeflow with ${KF_VERSION}..."
    info "::: ..."
    info "::: ..."
fi
